import { Icon } from '@iconify/react';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import React from 'react';
import Cta from '../../components/Cta';
import Div from '../../components/Div';
import Layout from '../../components/Layout';
import PageHeading from '../../components/PageHeading';
import Sidebar from '../../components/Sidebar.jsx';
import Spacing from '../../components/Spacing';

export default function BlogDetails() {
  const router = useRouter();
  const blogId = router.query.blogId;
  return (
    <>
      <Head>
        <title>Blog - {blogId}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        {/* Start Page Heading Section */}
        <PageHeading
          title="Blog Single"
          bgSrc="/images/blog_details_hero_bg.jpeg"
          pageLinkText={blogId}
        />
        {/* End Page Heading Section */}

        {/* Start Blog Details */}
        <Spacing lg="150" md="80" />
        <Div className="container">
          <Div className="row">
            <Div className="col-lg-8">
              {/* Start Details Post Content */}
              <Div className="cs-post cs-style2">
                <Div className="cs-post_thumb cs-radius_15">
                  <img
                    src="/images/post_4.jpeg"
                    alt="Post"
                    className="w-100 cs-radius_15"
                  />
                </Div>
                <Div className="cs-post_info">
                  <Div className="cs-post_meta cs-style1 cs-ternary_color cs-semi_bold cs-primary_font">
                    <span className="cs-posted_by">8th September 2023</span>
                    <Link href="/blog" className="cs-post_avatar">
                      Tech
                    </Link>
                  </Div>
                  <h2 className="cs-post_title">
                  The Digital Storefront: Why Small-Scale Businesses Need Websites
                  </h2>
                  <p>
                  Introduction: In today's fast-paced digital age, having a strong online presence is crucial for businesses of all sizes.
                  For small-scale businesses, a well-designed website can be a game-changer. In this blog post, we'll delve into the reasons 
                  why small businesses need websites and how they can leverage them to boost sales, attract, retain customers, and increase repeat purchases.
                  </p>
                
                  <p>
                    <h3>1. Why Your Small Business Needs a Website:</h3>
                    24/7 Accessibility: A website provides round-the-clock accessibility to your products or services, allowing potential customers to browse and shop at their convenience.
                    Credibility and Trust: A professionally designed website instills trust in your brand, making customers more likely to choose your business over competitors.
                    Expanded Reach: With a website, your business can reach a global audience, not just a local one.
                    Cost-Effective Marketing: Compared to traditional advertising, a website is a cost-effective marketing tool that offers better tracking and analytics.<br/><br/>
                    <h3>2. Boosting Sales with Your Website:</h3>
                    E-commerce Integration: Implement an easy-to-navigate online store to facilitate seamless transactions.
                    Product Showcase: Highlight your best products or services with compelling visuals and detailed descriptions.
                    Customer Reviews: Encourage satisfied customers to leave reviews, building trust and influencing potential buyers.<br/><br/>
                    <h3>3. Attracting and Retaining Customers:</h3>
                    Search Engine Optimization (SEO): Optimize your website for search engines to increase visibility and attract organic traffic.
                    Engaging Content: Regularly update your website with valuable content, such as blogs, articles, and videos, to keep visitors engaged.
                    Email Marketing: Collect customer emails and send personalized offers and updates to keep them coming back.<br/><br/>
                    <h3>4. Encouraging Repeat Purchases:</h3>
                    Loyalty Programs: Implement loyalty programs and reward schemes to incentivize repeat business.
                    Personalized Recommendations: Use data analytics to provide customers with personalized product recommendations.
                    Responsive Customer Support: Offer excellent customer service through your website to resolve issues promptly.<br/><br/>
                    <h3>Conclusion:</h3>
                    In conclusion, a website is a powerful tool for small-scale businesses to thrive in the digital era. It not only boosts sales but also attracts and retains customers, encouraging repeat purchases. As a growing business, it's essential to consider implementing these strategies to enhance your clients' online presence and overall success.
                    Remember, this is a broad overview, and the specific implementation of these strategies will depend on your clients' unique needs and goals. Feel free to adapt and adjust these recommendations as necessary to align with your current projects and objectives, such as client acquisition and marketing efforts. If you need further assistance or specific action plans, please don't hesitate to reach out Semantix labs.
                  </p>
                  
                </Div>
              </Div>
              {/* End Details Post Content */}

              {/* Start Comment Section */}
              <Spacing lg="30" md="30" />
              <h2 className="cs-font_50 cs-m0">Leave A Reply</h2>
              <Spacing lg="5" md="5" />
              <p className="cs-m0">
                Your email address will not be published. Required fields are
                marked *
              </p>
              <Spacing lg="40" md="30" />
              <form className="row">
                <Div className="col-lg-6">
                  <label>Full Name*</label>
                  <input type="text" className="cs-form_field" />
                  <Div className="cs-height_20 cs-height_lg_20" />
                  <Div
                    data-lastpass-icon-root="true"
                    style={{
                      position: 'relative !important',
                      height: '0px !important',
                      width: '0px !important',
                      float: 'left !important',
                    }}
                  />
                </Div>
                <Div className="col-lg-6">
                  <label>Email*</label>
                  <input type="text" className="cs-form_field" />
                  <Div className="cs-height_20 cs-height_lg_20" />
                </Div>
                <Div className="col-lg-12">
                  <label>Website*</label>
                  <input type="text" className="cs-form_field" />
                  <Div className="cs-height_20 cs-height_lg_20" />
                </Div>
                <Div className="col-lg-12">
                  <label>Write Your Comment*</label>
                  <textarea cols={30} rows={7} className="cs-form_field" />
                  <Div className="cs-height_25 cs-height_lg_25" />
                </Div>
                <Div className="col-lg-12">
                  <button className="cs-btn cs-style1">
                    <span>Send Message</span>
                    <Icon icon="bi:arrow-right" />
                  </button>
                </Div>
              </form>
              {/* End Comment Section */}
            </Div>
            
          </Div>
        </Div>
        <Spacing lg="150" md="80" />
        {/* Start Blog Details */}

        {/* Start CTA Section */}
        <Div className="container">
          <Cta
            title="Let’s disscuse make <br />something <i>cool</i> together"
            btnText="Apply For Meeting"
            btnLink="/contact"
            bgSrc="/images/cta_bg.jpeg"
          />
        </Div>
        {/* End CTA Section */}
      </Layout>
    </>
  );
}
